import { createApp } from 'vue';
import App from './App.vue';
import router from './router.js';
import store from './assets/store/index.js';
import 'bootstrap/dist/js/bootstrap.bundle.js';
import 'bootstrap/dist/css/bootstrap.min.css';
import "@fontsource/vazir";
const app = createApp(App);
app.use(store);
app.use(router);
app.mount('#app');
